# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Corona tracker for Stutensee

on:
  schedule:
    - cron:  '15 8 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1
    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install --upgrade --upgrade-strategy eager -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run script
      run: |
        python stutensee-corona.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Daniel Weisser
        author_email: daniel.weisser@gmail.com
        message: 'Update CSV data'
        add: 'daten.csv'
    - name: Add new images
      run: |
        git status
        git add *.png _includes/aktuelle_inzidenz.md
        git stash
        git fetch
        git checkout gh-pages
        git checkout stash -- *.png _includes/aktuelle_inzidenz.md
    - name: Commit new images
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Daniel Weisser
        author_email: daniel.weisser@gmail.com
        message: 'Update images'
        branch: gh-pages
        add: '*.png _includes/aktuelle_inzidenz.md'
